# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'burned_area_detector_dialog_base.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_BurnedAreaDetectorDialogBase(object):
    def setupUi(self, BurnedAreaDetectorDialogBase):
        BurnedAreaDetectorDialogBase.setObjectName("BurnedAreaDetectorDialogBase")
        BurnedAreaDetectorDialogBase.resize(600, 550)
        self.verticalLayout = QtWidgets.QVBoxLayout(BurnedAreaDetectorDialogBase)
        self.verticalLayout.setObjectName("verticalLayout")
        self.descriptionLabel = QtWidgets.QLabel(BurnedAreaDetectorDialogBase)
        self.descriptionLabel.setWordWrap(True)
        self.descriptionLabel.setObjectName("descriptionLabel")
        self.verticalLayout.addWidget(self.descriptionLabel)
        self.inputGroupBox = QtWidgets.QGroupBox(BurnedAreaDetectorDialogBase)
        self.inputGroupBox.setObjectName("inputGroupBox")
        self.gridLayout = QtWidgets.QGridLayout(self.inputGroupBox)
        self.gridLayout.setObjectName("gridLayout")
        self.preFireLabel = QtWidgets.QLabel(self.inputGroupBox)
        self.preFireLabel.setObjectName("preFireLabel")
        self.gridLayout.addWidget(self.preFireLabel, 0, 0, 1, 1)
        self.preFireLayerComboBox = gui.QgsMapLayerComboBox(self.inputGroupBox)
        self.preFireLayerComboBox.setObjectName("preFireLayerComboBox")
        self.gridLayout.addWidget(self.preFireLayerComboBox, 0, 1, 1, 1)
        self.postFireLabel = QtWidgets.QLabel(self.inputGroupBox)
        self.postFireLabel.setObjectName("postFireLabel")
        self.gridLayout.addWidget(self.postFireLabel, 1, 0, 1, 1)
        self.postFireLayerComboBox = gui.QgsMapLayerComboBox(self.inputGroupBox)
        self.postFireLayerComboBox.setObjectName("postFireLayerComboBox")
        self.gridLayout.addWidget(self.postFireLayerComboBox, 1, 1, 1, 1)
        self.verticalLayout.addWidget(self.inputGroupBox)
        self.optionsGroupBox = QtWidgets.QGroupBox(BurnedAreaDetectorDialogBase)
        self.optionsGroupBox.setObjectName("optionsGroupBox")
        self.optionsLayout = QtWidgets.QVBoxLayout(self.optionsGroupBox)
        self.optionsLayout.setObjectName("optionsLayout")
        self.thresholdLayout = QtWidgets.QHBoxLayout()
        self.thresholdLayout.setObjectName("thresholdLayout")
        self.seedThresholdLabel = QtWidgets.QLabel(self.optionsGroupBox)
        self.seedThresholdLabel.setObjectName("seedThresholdLabel")
        self.thresholdLayout.addWidget(self.seedThresholdLabel)
        self.seedThresholdDoubleSpinBox = QtWidgets.QDoubleSpinBox(self.optionsGroupBox)
        self.seedThresholdDoubleSpinBox.setMinimum(0.0)
        self.seedThresholdDoubleSpinBox.setMaximum(1.0)
        self.seedThresholdDoubleSpinBox.setSingleStep(0.05)
        self.seedThresholdDoubleSpinBox.setProperty("value", 0.9)
        self.seedThresholdDoubleSpinBox.setObjectName("seedThresholdDoubleSpinBox")
        self.thresholdLayout.addWidget(self.seedThresholdDoubleSpinBox)
        self.growThresholdLabel = QtWidgets.QLabel(self.optionsGroupBox)
        self.growThresholdLabel.setObjectName("growThresholdLabel")
        self.thresholdLayout.addWidget(self.growThresholdLabel)
        self.growThresholdDoubleSpinBox = QtWidgets.QDoubleSpinBox(self.optionsGroupBox)
        self.growThresholdDoubleSpinBox.setMinimum(0.0)
        self.growThresholdDoubleSpinBox.setMaximum(1.0)
        self.growThresholdDoubleSpinBox.setSingleStep(0.05)
        self.growThresholdDoubleSpinBox.setProperty("value", 0.1)
        self.growThresholdDoubleSpinBox.setObjectName("growThresholdDoubleSpinBox")
        self.thresholdLayout.addWidget(self.growThresholdDoubleSpinBox)
        self.optionsLayout.addLayout(self.thresholdLayout)
        self.maskCloudsCheckBox = QtWidgets.QCheckBox(self.optionsGroupBox)
        self.maskCloudsCheckBox.setChecked(True)
        self.maskCloudsCheckBox.setObjectName("maskCloudsCheckBox")
        self.optionsLayout.addWidget(self.maskCloudsCheckBox)
        self.maskWaterCheckBox = QtWidgets.QCheckBox(self.optionsGroupBox)
        self.maskWaterCheckBox.setChecked(True)
        self.maskWaterCheckBox.setObjectName("maskWaterCheckBox")
        self.optionsLayout.addWidget(self.maskWaterCheckBox)
        self.verticalLayout.addWidget(self.optionsGroupBox)
        self.outputGroupBox = QtWidgets.QGroupBox(BurnedAreaDetectorDialogBase)
        self.outputGroupBox.setObjectName("outputGroupBox")
        self.outputLayout = QtWidgets.QHBoxLayout(self.outputGroupBox)
        self.outputLayout.setObjectName("outputLayout")
        self.outputLineEdit = QtWidgets.QLineEdit(self.outputGroupBox)
        self.outputLineEdit.setObjectName("outputLineEdit")
        self.outputLayout.addWidget(self.outputLineEdit)
        self.outputFilePushButton = QtWidgets.QPushButton(self.outputGroupBox)
        self.outputFilePushButton.setObjectName("outputFilePushButton")
        self.outputLayout.addWidget(self.outputFilePushButton)
        self.verticalLayout.addWidget(self.outputGroupBox)
        self.buttonBox = QtWidgets.QDialogButtonBox(BurnedAreaDetectorDialogBase)
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.verticalLayout.addWidget(self.buttonBox)
        self.helpPushButton = QtWidgets.QPushButton(BurnedAreaDetectorDialogBase)
        self.helpPushButton.setObjectName("helpPushButton")
        self.verticalLayout.addWidget(self.helpPushButton)

        self.retranslateUi(BurnedAreaDetectorDialogBase)
        self.buttonBox.accepted.connect(BurnedAreaDetectorDialogBase.accept)
        self.buttonBox.rejected.connect(BurnedAreaDetectorDialogBase.reject)
        QtCore.QMetaObject.connectSlotsByName(BurnedAreaDetectorDialogBase)

    def retranslateUi(self, BurnedAreaDetectorDialogBase):
        _translate = QtCore.QCoreApplication.translate
        BurnedAreaDetectorDialogBase.setWindowTitle(_translate("BurnedAreaDetectorDialogBase", "Burned Area Detector"))
        self.descriptionLabel.setText(_translate("BurnedAreaDetectorDialogBase", "<h3>Burned Area Detector Plugin</h3>\n"
"<p>Detect burned areas from Sentinel-2 satellite imagery using fuzzy logic and region growing.</p>"))
        self.inputGroupBox.setTitle(_translate("BurnedAreaDetectorDialogBase", "Input Images"))
        self.preFireLabel.setText(_translate("BurnedAreaDetectorDialogBase", "Pre-fire Image:"))
        self.postFireLabel.setText(_translate("BurnedAreaDetectorDialogBase", "Post-fire Image:"))
        self.optionsGroupBox.setTitle(_translate("BurnedAreaDetectorDialogBase", "Processing Options"))
        self.seedThresholdLabel.setText(_translate("BurnedAreaDetectorDialogBase", "Seed Threshold:"))
        self.growThresholdLabel.setText(_translate("BurnedAreaDetectorDialogBase", "Grow Threshold:"))
        self.maskCloudsCheckBox.setText(_translate("BurnedAreaDetectorDialogBase", "Mask clouds and cloud shadows"))
        self.maskWaterCheckBox.setText(_translate("BurnedAreaDetectorDialogBase", "Mask water bodies"))
        self.outputGroupBox.setTitle(_translate("BurnedAreaDetectorDialogBase", "Output"))
        self.outputLineEdit.setPlaceholderText(_translate("BurnedAreaDetectorDialogBase", "Select output file path..."))
        self.outputFilePushButton.setText(_translate("BurnedAreaDetectorDialogBase", "Browse..."))
        self.helpPushButton.setText(_translate("BurnedAreaDetectorDialogBase", "Help"))
from qgis import gui


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    BurnedAreaDetectorDialogBase = QtWidgets.QDialog()
    ui = Ui_BurnedAreaDetectorDialogBase()
    ui.setupUi(BurnedAreaDetectorDialogBase)
    BurnedAreaDetectorDialogBase.show()
    sys.exit(app.exec_())
